# Generated by Django 4.2.14 on 2024-12-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserProfile.country",
                    ),
                ),
            ],
        ),
    ]
