# Generated by Django 4.2.14 on 2024-12-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0002_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserProfile.state",
            ),
        ),
    ]
