# Generated by Django 4.2.14 on 2024-12-23 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0003_city_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="city",
            name="state",
        ),
    ]
