# Generated by Django 4.2.14 on 2024-12-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0004_remove_city_country_remove_city_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserProfile.state",
            ),
            preserve_default=False,
        ),
    ]
