# Generated by Django 4.2.14 on 2025-04-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0005_city_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="profile_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
