# Generated by Django 4.2.14 on 2025-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0006_agent_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="bio",
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
