# Generated by Django 4.2.14 on 2025-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0007_agent_bio_agent_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
