# Generated by Django 4.0.5 on 2024-06-23 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterCustomerChat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 14, 23, 9, 801728))),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.customer')),
                ('hc_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.helpcenteruser')),
                ('sent_from', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentBuyerMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 14, 23, 9, 804442))),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.agent')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.buyer')),
                ('sent_from', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
