# Generated by Django 4.0.5 on 2024-06-30 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbuyermessage',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 22, 32, 4, 972132)),
        ),
        migrations.AlterField(
            model_name='helpcentercustomerchat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 22, 32, 4, 972132)),
        ),
        migrations.CreateModel(
            name='AgentBuyerContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.buyer')),
            ],
        ),
    ]
