# Generated by Django 4.0.5 on 2024-07-01 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_agentbuyermessage_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentbuyercontact',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AlterField(
            model_name='agentbuyermessage',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 14, 59, 0, 821618)),
        ),
        migrations.AlterField(
            model_name='helpcentercustomerchat',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 14, 59, 0, 821618)),
        ),
    ]
