# Generated by Django 4.2.14 on 2024-09-24 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_user_agentbuyercontact_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 25, 2, 44, 56, 396195)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 25, 2, 44, 56, 396195)
            ),
        ),
    ]
