# Generated by Django 4.2.14 on 2024-10-13 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_agentbuyermessage_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 13, 6, 21, 55, 335510)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 13, 6, 21, 55, 334431)
            ),
        ),
    ]
