# Generated by Django 4.2.14 on 2024-10-13 00:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_alter_agentbuyermessage_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyercontact",
            name="agent",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyercontact",
            name="buyer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 13, 6, 27, 47, 954098)
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="sent_from",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="customer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.customer",
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 13, 6, 27, 47, 946270)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="hc_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.helpcenteruser",
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="sent_from",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
