# Generated by Django 4.2.14 on 2024-10-13 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_agentbuyercontact_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 14, 1, 19, 57, 155734)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 14, 1, 19, 57, 155734)
            ),
        ),
    ]
