# Generated by Django 4.2.14 on 2024-12-23 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0022_alter_agentbuyermessage_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 23, 23, 32, 39, 536556)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 23, 23, 32, 39, 522545)
            ),
        ),
    ]
