# Generated by Django 4.2.14 on 2025-03-15 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0034_alter_agentbuyermessage_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentbuyermessage",
            name="agent_buyer_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.agentbuyercontact",
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 15, 11, 13, 45, 600439)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 15, 11, 13, 45, 600439)
            ),
        ),
    ]
