# Generated by Django 4.2.14 on 2025-03-15 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0035_agentbuyermessage_agent_buyer_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentbuyermessage",
            old_name="agent_buyer_message",
            new_name="agent_buyer_contact",
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 15, 11, 14, 40, 443222)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 15, 11, 14, 40, 427599)
            ),
        ),
    ]
