# Generated by Django 4.2.14 on 2025-03-19 07:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "chat",
            "0036_rename_agent_buyer_message_agentbuyermessage_agent_buyer_contact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 19, 13, 16, 22, 479715)
            ),
        ),
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="sent_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 19, 13, 16, 22, 479715)
            ),
        ),
    ]
