# Generated by Django 4.2.14 on 2025-05-17 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0046_alter_agentbuyermessage_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbuyermessage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 17, 11, 27, 32, 882677)
            ),
        ),
        migrations.AlterField(
            model_name="helpcentercustomerchat",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 17, 11, 27, 32, 882677)
            ),
        ),
    ]
