# Generated by Django 4.0.5 on 2024-06-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('number_of_garages', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('area', models.FloatField()),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('available_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.agent')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.country')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Estates.estatestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.country')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('media_id', models.IntegerField(primary_key=True, serialize=False)),
                ('media_path', models.FileField(upload_to='MEDIA')),
                ('is_thumbnail', models.BooleanField()),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estates.house')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estates.land')),
            ],
        ),
    ]
