# Generated by Django 4.2.14 on 2024-09-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0001_initial"),
        ("Estates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="agent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="UserProfile.agent",
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="available_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Estates.estatestatus",
            ),
        ),
    ]
