# Generated by Django 4.2.14 on 2024-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0002_land_agent_land_available_date_land_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="house_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
