# Generated by Django 4.2.14 on 2024-09-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0001_initial"),
        ("Estates", "0003_alter_house_house_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="UserProfile.agent",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Estates.estatestatus"
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="UserProfile.agent",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="land_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="land",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Estates.estatestatus",
            ),
        ),
    ]
