# Generated by Django 4.2.14 on 2024-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0004_alter_house_agent_alter_house_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymedia",
            name="media_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
