# Generated by Django 4.2.14 on 2024-10-13 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0001_initial"),
        ("Estates", "0006_alter_house_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserProfile.agent",
            ),
        ),
    ]
