# Generated by Django 4.2.14 on 2024-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0007_alter_land_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="address_line_1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="address_line_2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
