# Generated by Django 4.2.14 on 2024-12-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0008_house_latitude_house_longitude_land_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
