# Generated by Django 4.2.14 on 2024-12-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0005_city_state"),
        ("Estates", "0009_alter_house_address_line_2_alter_house_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserProfile.state",
            ),
            preserve_default=False,
        ),
    ]
