# Generated by Django 4.2.14 on 2025-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0010_house_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="house",
            name="address_line_2",
        ),
        migrations.AddField(
            model_name="house",
            name="cooling",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="heating",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="listed_length",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="street",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="year_built",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
