# Generated by Django 4.2.14 on 2025-05-11 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0011_remove_house_address_line_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="listed_length",
            new_name="listed_date",
        ),
    ]
