# Generated by Django 4.2.14 on 2025-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0012_rename_listed_length_house_listed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="zip_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
