# Generated by Django 4.2.14 on 2025-05-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0008_agent_phone_number"),
        ("Estates", "0013_house_zip_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVisitRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("time_slot", models.CharField(max_length=50, null=True)),
                ("time", models.TimeField(null=True)),
                ("extra_note", models.TextField(null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserProfile.buyer",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Estates.house"
                    ),
                ),
            ],
        ),
    ]
