# Generated by Django 4.2.14 on 2025-05-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Estates", "0014_propertyvisitrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVisitTimeSlots",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time_slot", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="propertyvisitrequest",
            name="time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Estates.propertyvisittimeslots",
            ),
        ),
    ]
